name: Npm Package

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: cd layout-kit-react && yarn
            - run: cd layout-kit-react && yarn test
            - run: cd layout-kit-react && tsc
            - run: cd layout-kit-react && tsc -m es6 --outDir esm
            - name: Bump version
              uses: remorses/bump-version@js
              with:
                  version_file: layout-kit-react/VERSION
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: cd layout-kit-react && yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
